version: '0.2.0.{build}'
image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\projects\libskycoin-dotnet

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
environment:
  GOOS: windows
  GOARCH: amd64
  GOPATH: c:\projects\libskycoin-dotnet\gopath
  MINGW_W64: c:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64

stack: go 1.11

# Install dev dependencies
install:
  - set PATH=%MINGW_W64%\bin;%PATH%
  - cmd: cp %MINGW_W64%\bin\mingw32-make.exe %MINGW_W64%\bin\make.exe
  - cmd: git submodule update --init --recursive --remote
  - cmd: cd %GOPATH%
  - cmd: go get github.com/gz-c/gox
  - cmd: go get -t ./...
  
# scripts to run before build
# packages from nuget
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - nuget restore LibskycoinNet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

# use custom build_script
build_script:
  - msbuild /p:Configuration=Release LibskycoinNet.sln

# to run tests against only selected assemblies and/or categories
test:
  assemblies:
    only:
      - LibskycoinNetTest\bin\Release\LibskycoinNetTest.dll

      
deploy: off      