version: '0.2.0.{build}'
image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\projects\libskycoin-dotnet

environment:
  GOOS: windows
  GOARCH: amd64
  GOPATH: c:\projects\libskycoin-dotnet\gopath
  MINGW_W64: c:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64

stack: go 1.11

# Install dev dependencies
install:
  - set PATH=%MINGW_W64%\bin;%PATH%
  - cmd: cp %MINGW_W64%\bin\mingw32-make.exe %MINGW_W64%\bin\make.exe
  - cmd: git submodule update --init --recursive --remote
  - cmd: cd %GOPATH%
  - cmd: go get github.com/gz-c/gox
  - cmd: go get -t ./...
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: nuget restore LibskycoinNet.sln
  - cmd: nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                   # enable MSBuild parallel builds
  project: LibskycoinNet.sln       # path to Visual Studio solution or project
  publish_wap: false               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: false         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: false             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: false  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  # MSBuild verbosity level
  verbosity: detailed

# to run tests against only selected assemblies and/or categories
test:
  assemblies:
    only:
      - LibskycoinNetTest\bin\Release\LibskycoinNetTest.dll

deploy: off      