language: csharp
solution: LibskycoinNet.sln

matrix:
  include:
    - os: linux
      dist: xenial
      mono: 4.8.0
      env:
        - MONO_VERSION=4.8.0
    - os: linux
      dist: xenial
      dotnet: 2.1.500
      mono: none
      env:
        - DOTNETCORE=2
    - os: osx
      mono: 4.8.0
      env:
        - MONO_VERSION=4.8.0
    - os: osx
      dotnet: 2.1.500
      mono: none
      env:
        - DOTNETCORE=2

before-install:
  - if [ "$DOTNETCORE" != "" ] ; \
                            then export NUGET=dotnet DOTNET=dotnet; \
                            else export NUGET=nuget DOTNET=mono; \
                            fi

install:
  - $NUGET restore LibskycoinNet.sln
  - ./.travis/install-deps.sh
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
script:
  - msbuild /p:Configuration=Release LibskycoinNet.sln
  - $DOTNET ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LibskycoinNetTest/bin/Release/LibskycoinNetTest.dll
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
