language: csharp
solution: LibskycoinNet.sln
sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      mono: latest
      env:
        - MONO_VERSION=4.8.0
    - os: linux
      dist: xenial
      dotnet: 2.1.500
      mono: latest
      env:
        - DOTNETCORE=2
    - os: osx
      osx_image: xcode8
      mono: latest
      env:
        - MONO_VERSION=4.8.0
    - os: osx
      osx_image: xcode8
      dotnet: 2.1.500
      mono: latest
      env:
        - DOTNETCORE=2

before_install:
  - if [ "$DOTNETCORE" != "" ] ; then export DOTNET=dotnet; export MSBUILD='dotnet msbuild'; export NUGET="mono $(pwd)/.travis/bin/nuget.exe" ; else export DOTNET=mono; export MSBUILD=msbuild ; export NUGET=nuget ; fi
  - ./.travis/install-deps.sh
  - eval "CC=gcc-6 && CXX=g++-6"

install:
  - ./.travis/install-travis-gcc.sh
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then mkdir swig_build && cd swig_build && wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz && tar -zxf swig-3.0.12.tar.gz && cd swig-3.0.12 && sudo ./configure --prefix=/usr && sudo make && sudo make install && cd ../../ && sudo rm -rf swig_build ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null  && brew install swig && brew install gimme; fi
  - eval "$(gimme 1.11)"
  
script:
  - CC=gcc-6 make test
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
