language: csharp
solution: LibskycoinNet.sln

matrix:
  include:
    - os: linux
      dist: xenial
      mono: 4.8.0
      env:
        - MONO_VERSION=4.8.0
    - os: linux
      dist: xenial
      dotnet: 2.1.500
      mono: none
      env:
        - DOTNETCORE=2
    - os: osx
      mono: 4.8.0
      env:
        - MONO_VERSION=4.8.0
    - os: osx
      dotnet: 2.1.500
      mono: none
      env:
        - DOTNETCORE=2

before_install:
  - if [ "$DOTNETCORE" != "" ] ; then export DOTNET=dotnet; export MSBUILD='dotnet build'; export RESTORE='dotnet restore' ; export INSTALLPKG='dotnet add package' ; else export DOTNET=mono; export MSBUILD=msbuild ; export RESTORE='nuget restore' ; INSTALLiPKG='nuget install' ; fi
  - ./.travis/install-deps.sh

install:
  - $MSBUILD -version
  - $RESTORE LibskycoinNet.sln
  - .travis/installpkg.sh NUnit.Runners 2.6.4 testrunner
  
script:
  - $MSBUILD /p:Configuration=Release LibskycoinNet.sln
  - $DOTNET ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LibskycoinNetTest/bin/Release/LibskycoinNetTest.dll
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
