language: csharp
solution: LibskycoinNet.sln

matrix:
  include:
    - os: linux
      language: csharp
      dist: xenial
      mono: 4.8.0
      env:
        - MONO_VERSION=4.8.0
    - os: osx
      languague: csharp
      mono: 4.8.0
      env:
        - MONO_VERSION=4.8.0

install:
  - nuget restore LibskycoinNet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - ./.travis/install-deps.sh
  
script:
  - msbuild /p:Configuration=Release LibskycoinNet.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LibskycoinNetTest/bin/Release/LibskycoinNetTest.dll
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
