sudo: required
language: csharp
solution: LibskycoinNet.sln

matrix:
  include:
    - os: linux
      dist: xenial
      mono: 4.8.0
      dotnet: 2.1.500

    - os: osx
      dotnet: 2.1.500
      mono: 4.8.0

before_install:
  - ./.travis/install-deps.sh
  - ./.travis/install-travis-gcc.sh
  - eval "CC=gcc && CXX=g++"

install:
  - eval "$(gimme 1.10)"
  
script:
  - make test
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
