sudo: required
language: csharp
solution: LibSkycoinDotNet.sln

matrix:
  include:
    #- os: linux
    #  dist: bionic
    #  mono: latest
    #  dotnet: 2.2.102

    - os: osx
      dotnet: 2.2.102
      mono: 4.8.0

before_install:
  - ./.travis/install-deps.sh
  - ./.travis/install-travis-gcc.sh
  - eval "CC=gcc && CXX=g++"

install:
  - eval "$(gimme 1.10)"
  
script:
  - make test
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
