language: csharp
solution: LibskycoinNet.sln

matrix:
  include:
    - os: linux
      dist: xenial
      mono: latest
      env:
        - MONO_VERSION=4.8.0
    - os: linux
      dist: xenial
      dotnet: 2.1.500
      mono: latest
      env:
        - DOTNETCORE=2
    - os: osx
      mono: latest
      env:
        - MONO_VERSION=4.8.0
    - os: osx
      dotnet: 2.1.500
      mono: latest
      env:
        - DOTNETCORE=2

before_install:
  - if [ "$DOTNETCORE" != "" ] ; then export DOTNET=dotnet; export MSBUILD='dotnet msbuild'; export NUGET="mono $(pwd)/.travis/bin/nuget.exe" ; else export DOTNET=mono; export MSBUILD=msbuild ; export NUGET=nuget ; fi
  - ./.travis/install-deps.sh

install:
  - eval "$(gimme 1.11)"
  - go version
  - mkdir swig_build 
  - cd swig_build 
  - wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz 
  - tar -zxf swig-3.0.12.tar.gz 
  - cd swig-3.0.12 
  - sudo ./configure --prefix=/usr 
  - sudo make 
  - sudo make install 
  - cd ../../ 
  - sudo rm -rf swig_build
  
script:
  - make test
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
