sudo: required
language: csharp

matrix:
  include:
    - os: linux
      dist: xenial
      mono: latest
      solution: LibskycoinNet.sln
      env: TYPE=mono
    - os: linux
      dist: xenial
      dotnet: 2.2.102
      solution: LibSkycoinDotNet.sln
      env: TYPE=dotnet

    #- os: osx
    #  dotnet: 2.2.102
    #  mono: 4.8.0

before_install:
  - ./.travis/install-deps.sh
  - ./.travis/install-travis-gcc.sh
  - eval "CC=gcc && CXX=g++"
  - eval "DYLD_LIBRARY_PATH=PWD/build/usr/lib"
  - eval "LD_LIBRARY_PATH=PWD/build/usr/lib"


install:
  - eval "$(gimme 1.10)"
  
script:
  - make test-$(TYPE)
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
