language: csharp
solution: LibskycoinNet.sln

before_install:
  - sudo apt-get install -y gendarme

install:
  - nuget restore LibskycoinNet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
script:
  - msbuild /p:Configuration=Release LibskycoinNet.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LibskycoinNetTest/bin/Release/LibskycoinNetTest.dll
  - make lint
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
