language: csharp
solution: LibskycoinNet.sln

matrix:
  include:
    - os: linux
      dist: xenial
      mono: 4.8.0
      env:
        - MONO_VERSION=4.8.0
    - os: linux
      dist: xenial
      dotnet: 2.2.100
      mono: none
      env:
        - DOTNETCORE=2
    - os: osx
      mono: 4.8.0
      env:
        - MONO_VERSION=4.8.0
    - os: osx
      dotnet: 2.2.100
      mono: none
      env:
        - DOTNETCORE=2

install:
  - if [ "${DOTNETCORE}" != "" ] ; then dotnet add package NuGet.CommandLine --version 4.7.1 --package-directory /usr/local/bin ; ls -l /usr/local/nuget* ; fi
  - nuget restore LibskycoinNet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - ./.travis/install-deps.sh
  
script:
  - msbuild /p:Configuration=Release LibskycoinNet.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LibskycoinNetTest/bin/Release/LibskycoinNetTest.dll
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
