language: csharp
solution: LibskycoinNet.sln

os:
  - linux
  - osx

mono:
  - 4.8.0

install:
  - nuget restore LibskycoinNet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
script:
  - msbuild /p:Configuration=Release LibskycoinNet.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LibskycoinNetTest/bin/Release/LibskycoinNetTest.dll
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
